### ISSUE TITLE
Suggestion : Retirer JSON.stringify dans les contrôleurs

### ISSUE THREAD

**Issue by obrassard** [yvanross/log210-systeme-gestion-bordereau-node-express-ts#1]
Salut ! J'ai fait différent tests de requêtes vers le SGB et j'aurais une suggestion pour vous. 
En effet, je crois qu'il serait plus pratique de retirer les `JSON.stringify` des valeurs de retours dans les différentes opérations systèmes. 

Par exemple dans `SgbController.ts:courses()`, pourquoi ne pas retourner directement `return teacher.courses()`, plutôt que `return JSON.stringify(teacher.courses())`?

Le problème est qu'en utilisant JSON.stringify, les données retournées dans l'objet `data` de la réponse sont retourné comme string, et non en array JSON, voici un exemple dans postman : 

Avec JSON.stringify : 
<img width="1123" alt="Capture d’écran, le 2020-09-27 à 10 29 02" src="https://user-images.githubusercontent.com/17227551/94367436-cede9280-00ac-11eb-8446-a94fde0103a5.png">

Sans JSON.stringify : 
<img width="658" alt="Capture d’écran, le 2020-09-27 à 10 28 27" src="https://user-images.githubusercontent.com/17227551/94367441-db62eb00-00ac-11eb-9172-d6be850b2e15.png">

Le fait que l'objet `data` soit un string cause notamment des problèmes avec ce code (dans l'exemple fourni) : 
```ts
return fetch(urlServeurSGB + endPointGroupeCoursEnseignant, { headers: { token: md5(teacherId) } })
            .then((res) => res.json())
            .then((data) = data.map((groupeCoursSGB: any) => formatGroupeCours(groupeCoursSGB))})
            .catch((err: any) => {
                console.log(err)
                return console.log("Erreur avec SGB");
            });
```
En effet, un erreur est lancée lorsqu'on fait `data.map`, puisqu'à ce moment `data` est un string, et non pas un tableau.
Il es possible de corriger ça côté client, en utilisant un `then((res) => res.json()).then((res) => JSON.parse(res.data))...` pour parser l'objet data, mais il me semble que ce serait plus logique et pratique si SGB retournait directement un JSON valide qu'il ne faudrait pas parser en deux temps.

Merci d'avance !

**Comment by massicottem** [comment]
Je vais essayer de faire les modifications! 😉
