### ISSUE TITLE
Les champs reçus par l'api sont mal nommés

### ISSUE THREAD

**Issue by Leuchak** [yvanross/log210-systeme-gestion-bordereau-node-express-ts#13]
La documentation /docs/index.html nous donne le format JSON retourné par les appels à l'API.
Mais les champs retourné ont tous un underscore devant leur nom.

Par exemple, la commande `curl -H 'token: 72ca7603567fdca12a338d4cbe963458' http://localhost:3001/api/v1/courses`
 Renvoit:
```json
{
  "message": "Success",
  "data": [
    {
      "_id": 2,
      "_sigle": "LOG210",
      "_nb_max_student": 5,
      "_groupe": "02",
      "_titre": "Analyse et conception de logiciels",
      "_date_debut": "2019-09-02",
      "_date_fin": "2019-10-03"
    },
    {
      "_id": 3,
      "_sigle": "LOG210",
      "_nb_max_student": 5,
      "_groupe": "03",
      "_titre": "Analyse et conception de logiciels",
      "_date_debut": "2019-09-03",
      "_date_fin": "2019-11-04"
    }
  ]
}
```

La réponse JSON ne devrait pas contenir de underscore selon la documentation.
Le type des donnés affiché dans la documentation ne réflete pas non plus le type des données retourné par les requètes.

**Comment by fuhrmanator** [comment]
Merci pour la issue - votre feedback est apprécié!

**Comment by yvanross** [comment]
C'est corrigé
