### ISSUE TITLE
un étudiant ne devrait pas soumettre ses notes

### ISSUE THREAD

**Issue by fuhrmanator** [yvanross/log210-systeme-gestion-bordereau-node-express-ts#16]
Dans le contexte de SGA/SGB, je crois que le use-case est qu'un étudiant passe un quiz, le quiz est évalué (automatiquement) par le système SGA, et c'est SGA qui soumet le résultat à SGB afin que l'enseignant ne soit pas obligé d'importer les notes plus tard. Dans ce cas, c'est SGA (un genre de "superuser") qui se connecte à SGB pour transmettre la note. 

Voici un DSS:

![DSS_SGA_SGB](https://www.plantuml.com/plantuml/svg/PP0nJWD134NxEOMLAYdO0wH08GBHHKBRHaBEheaC6Szaneu2DyX9ECXU3Cyg7SLCuV_r_hStLR6enHCyz_rx__haRnlg5ql6WX6gVf_8_y93SmKSD1LOhAURsiWekW2iGC7ToWDddxZgd7bUZ_XFsTwLG-Yw3eOaIbSb60dEnZ_WTg0hnUonRWW43u-D0sjGAf65ofjHLKuYo8MMgvap_I9aCeLSICRYF7D_p7M6IFA4TA5o9qst2vuC6mG-a9NsWgOf-kHi5Cch9jkt4u09l4WbFeelq5YDC5SwE0W_atcjdVENBgx2njFzJdy0 "DSS_SGA_SGB")

Si on fait l'hypothèse que SGB soit l'équivalent de SIGNETS, un.e étudiant.e pourrait consulter ses notes sur SGB. Pour eux c'est un système read-only. 

Dans [l'API](https://cc-yvanross.github.io/8e8addd727f14edfd8c50bd99633c611956f0439/dist/docs/index.html#api-Etudiant-GetV1StudentNoteCourseCourseTypeTypeType_idType_idNoteNote) ça devrait être sous une autre rubrique (genre Administrateur, c-a-d l'équivalent de SGA avec les permissions?)

**Comment by yvanross** [comment]
Problème à gérer au niveau de SGA.
