### ISSUE TITLE
change port 3001 to 3200 to prevent conflic on student computer

### ISSUE THREAD

**Issue by yvanross** [yvanross/log210-systeme-gestion-bordereau-node-express-ts#5]

**Comment by Leuchak** [comment]
Il semblerait que le problème soit lié à la commande `npm start`.
> "start": "apidoc -i src/routes/ -o dist/docs/ & node dist/index.js & open http://127.0.0.1:3001",

Les commandes sont executé en background sur les système basé sur UNIX.
Il est possible que le process soit resté ouvert.

**Comment by Leuchak** [comment]
Je confirme 
![image](https://user-images.githubusercontent.com/21264237/123536420-36874400-d6f8-11eb-98c9-f4f6cd541b57.png)

**Comment by yvanross** [comment]
Done
