### ISSUE TITLE
Ajouter un Lien de Ping

### ISSUE THREAD

**Issue by Ronin825** [yvanross/log210-systeme-gestion-bordereau-node-express-ts#6]
Il serait interesant d'avoir une route basic pour pouvoir verifier l'etat du serveur SGB. Ceci pourrait servir pour les tests et l'application SGA pour s'assurer que le SGB est en ligne. Ceci peut aussi nous permettre d'informer l'utilisateur dans un cas de probleme.

ex : 
req : http://\<sgb addr\>:\<port\>/ping

response : 200 (OK) avec message success
  ou un timeout s'il n'est pas up.

**Comment by yvanross** [comment]
C'est fait.
