### ISSUE TITLE
Identification des comptes Enseignants/Etudiant

### ISSUE THREAD

**Issue by Ronin825** [yvanross/log210-systeme-gestion-bordereau-node-express-ts#7]
Il faudrait ajouter un champ dans la reponse d'authentification qui nous permette de differencier les comptes etudiants et enseignants. 

Ceci nous permettrait d'ajuster les options disponibles a l'utilisateur selon son type de compte.

**Comment by yvanross** [comment]
Login avec deux routes différentes.
